/****************************************************************************************************
*Description:  Utility class

*Revision   |Date          |Author             |AdditionalNotes
*====================================================================================================
*   1.0     06/24/2016      Karan      This class is being used to restrict execution of block of code
                                       which we don't want to execute.
                                             
* Test Class -    
*****************************************************************************************************/

public Class Utility{
    public static boolean RunOnce = true;
    public static boolean IsFromLeadInsert = true;
}